import type {
  CameraModeDto,
  CameraDto,
  DwgImportResultDto,
  ExportBundleDto,
  LayoutCameraDto,
  LayoutResultDto,
  LayoutSolveRequestDto,
  ProjectCreateDto,
  ProjectDto,
  PointDto,
  RecognitionConfidenceItemDto,
  RecognitionResultDto,
  ScaleState,
  SegmentDto
} from "../features/workbench/types";

const API_PREFIX = "/api";

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function parseScaleState(value: unknown): ScaleState | null {
  if (value === null) {
    return null;
  }

  if (!isObject(value) || typeof value.source !== "string") {
    throw new Error("Invalid scale state");
  }

  const unitsPerMeter =
    typeof value.unitsPerMeter === "number"
      ? value.unitsPerMeter
      : typeof value.pixelsPerMeter === "number"
        ? value.pixelsPerMeter
        : null;

  if (unitsPerMeter === null) {
    throw new Error("Invalid scale state");
  }

  return {
    unitsPerMeter,
    pixelsPerMeter:
      typeof value.pixelsPerMeter === "number" ? value.pixelsPerMeter : unitsPerMeter,
    source: value.source
  };
}

function parseViewport(value: unknown) {
  if (
    !isObject(value) ||
    typeof value.min_x !== "number" ||
    typeof value.min_y !== "number" ||
    typeof value.max_x !== "number" ||
    typeof value.max_y !== "number" ||
    typeof value.width !== "number" ||
    typeof value.height !== "number"
  ) {
    throw new Error("Invalid DWG viewport");
  }

  return {
    minX: value.min_x,
    minY: value.min_y,
    maxX: value.max_x,
    maxY: value.max_y,
    width: value.width,
    height: value.height
  };
}

function parseDwgImportWarning(value: unknown) {
  if (
    !isObject(value) ||
    typeof value.id !== "string" ||
    typeof value.message !== "string" ||
    typeof value.severity !== "string"
  ) {
    throw new Error("Invalid DWG warning");
  }

  return {
    id: value.id,
    message: value.message,
    severity: value.severity,
    sourcePath: typeof value.source_path === "string" ? value.source_path : undefined,
    sourceType: typeof value.source_type === "string" ? value.source_type : undefined
  };
}

function parsePoint(value: unknown): PointDto {
  if (!isObject(value) || typeof value.x !== "number" || typeof value.y !== "number") {
    throw new Error("Invalid point");
  }

  return { x: value.x, y: value.y };
}

function parseCameraMode(value: unknown): CameraModeDto {
  if (value !== "directional" && value !== "panoramic") {
    throw new Error("Invalid camera mode");
  }

  return value;
}

function parseExportBundleDto(value: unknown): ExportBundleDto {
  if (
    !isObject(value) ||
    typeof value.png_path !== "string" ||
    typeof value.pdf_path !== "string" ||
    typeof value.project_path !== "string"
  ) {
    throw new Error("Invalid export payload");
  }

  return {
    pngPath: value.png_path,
    pdfPath: value.pdf_path,
    projectPath: value.project_path
  };
}

function parseRecognitionConfidenceItem(value: unknown): RecognitionConfidenceItemDto {
  if (
    !isObject(value) ||
    typeof value.id !== "string" ||
    typeof value.message !== "string" ||
    typeof value.severity !== "string"
  ) {
    throw new Error("Invalid recognition confidence item");
  }

  return {
    id: value.id,
    message: value.message,
    severity: value.severity
  };
}

function parseSegment(value: unknown): SegmentDto {
  if (
    !isObject(value) ||
    (typeof value.id !== "string" &&
      typeof value.id !== "undefined" &&
      value.id !== null) ||
    !isObject(value.start) ||
    !isObject(value.end)
  ) {
    throw new Error("Invalid segment");
  }

  return {
    id: typeof value.id === "string" ? value.id : undefined,
    start: parsePoint(value.start),
    end: parsePoint(value.end)
  };
}

function parseLayoutCameraDto(value: unknown): LayoutCameraDto {
  if (!isObject(value) || typeof value.id !== "string" || !Array.isArray(value.coverage_polygon)) {
    throw new Error("Invalid layout camera");
  }

  return {
    id: value.id,
    mode: parseCameraMode(value.mode),
    position: parsePoint(value.position),
    directionDeg: typeof value.direction_deg === "number" ? value.direction_deg : null,
    coveragePolygon: value.coverage_polygon.map(parsePoint),
    isAutoGenerated: Boolean(value.is_auto_generated),
    isModified: Boolean(value.is_modified),
    locked: Boolean(value.locked)
  };
}

export function parseLayoutResultDto(value: unknown): LayoutResultDto {
  if (
    !isObject(value) ||
    typeof value.recommended_camera_count !== "number" ||
    typeof value.coverage_ratio !== "number" ||
    !Array.isArray(value.blind_spots) ||
    !Array.isArray(value.overlap_hints) ||
    !Array.isArray(value.cameras)
  ) {
    throw new Error("Invalid layout payload");
  }

  return {
    recommendedCameraCount: value.recommended_camera_count,
    coverageRatio: value.coverage_ratio,
    blindSpots: value.blind_spots.map(parsePoint),
    overlapHints: value.overlap_hints.map(parsePoint),
    cameras: value.cameras.map(parseLayoutCameraDto)
  };
}

export function parseProjectDto(value: unknown): ProjectDto {
  if (!isObject(value)) {
    throw new Error("Invalid project payload");
  }

  const { id, name, scale, cameras, walls, doors } = value;

  if (typeof id !== "string") {
    throw new Error("Invalid project id");
  }

  if (typeof name !== "string") {
    throw new Error("Invalid project name");
  }

  if (!Array.isArray(cameras) || !Array.isArray(walls) || !Array.isArray(doors)) {
    throw new Error("Invalid project collections");
  }

  return {
    id,
    name,
    scale: parseScaleState(scale),
    cameras: cameras as CameraDto[],
    walls: walls as SegmentDto[],
    doors: doors as SegmentDto[]
  };
}

export function parseRecognitionResultDto(value: unknown): RecognitionResultDto {
  if (
    !isObject(value) ||
    !Array.isArray(value.walls) ||
    !Array.isArray(value.doors) ||
    !Array.isArray(value.confidence_items)
  ) {
    throw new Error("Invalid recognition payload");
  }

  return {
    scale: parseScaleState(value.scale ?? null),
    walls: value.walls.map(parseSegment),
    doors: value.doors.map(parseSegment),
    confidenceItems: value.confidence_items.map(parseRecognitionConfidenceItem)
  };
}

export function parseDwgImportResultDto(value: unknown): DwgImportResultDto {
  if (
    !isObject(value) ||
    !Array.isArray(value.walls) ||
    !Array.isArray(value.doors) ||
    !Array.isArray(value.warnings) ||
    typeof value.unit_source !== "string"
  ) {
    throw new Error("Invalid DWG import payload");
  }

  const unitsPerMeter =
    typeof value.units_per_meter === "number" ? value.units_per_meter : null;

  if (unitsPerMeter === null) {
    throw new Error("Invalid DWG import payload");
  }

  return {
    unitsPerMeter,
    unitSource: value.unit_source,
    viewport: parseViewport(value.viewport),
    walls: value.walls.map(parseSegment),
    doors: value.doors.map(parseSegment),
    warnings: value.warnings.map(parseDwgImportWarning)
  };
}

async function requestProject(path: string, init: RequestInit): Promise<ProjectDto> {
  const response = await fetch(`${API_PREFIX}${path}`, init);

  if (!response.ok) {
    throw new Error(`Project request failed with status ${response.status}`);
  }

  return parseProjectDto(await response.json());
}

export function createProject(project: ProjectCreateDto): Promise<ProjectDto> {
  const payload: ProjectCreateDto = {
    name: project.name,
    scale: project.scale,
    cameras: project.cameras,
    walls: project.walls,
    doors: project.doors
  };

  return requestProject("/projects", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });
}

export function getProject(projectId: string): Promise<ProjectDto> {
  return requestProject(`/projects/${projectId}`, {
    method: "GET"
  });
}

export async function importDwgPlan(file: File): Promise<DwgImportResultDto> {
  const formData = new FormData();
  formData.append("file", file);

  const response = await fetch(`${API_PREFIX}/dwg/import`, {
    method: "POST",
    body: formData
  });

  if (!response.ok) {
    throw new Error(`DWG import failed with status ${response.status}`);
  }

  return parseDwgImportResultDto(await response.json());
}

export async function solveLayout(request: LayoutSolveRequestDto): Promise<LayoutResultDto> {
  const lockedCameras = request.lockedCameras?.map(cam => ({
    id: cam.id,
    mode: cam.mode,
    position: cam.position,
    direction_deg: cam.directionDeg,
    coverage_polygon: cam.coveragePolygon,
    is_auto_generated: cam.isAutoGenerated,
    is_modified: cam.isModified,
    locked: cam.locked
  })) ?? [];

  const response = await fetch(`${API_PREFIX}/layout/solve`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      scale: request.scale,
      coverage_distance_m: request.coverageDistanceM,
      camera_modes: request.cameraModes,
      walls: request.walls,
      doors: request.doors,
      region_polygon: request.regionPolygon,
      locked_cameras: lockedCameras,
      field_of_view_deg: request.fieldOfViewDeg ?? 120,
      ray_count: request.rayCount ?? 16
    })
  });

  if (!response.ok) {
    throw new Error(`Layout request failed with status ${response.status}`);
  }

  return parseLayoutResultDto(await response.json());
}

export async function recognizePlan(file: File, regionPolygon?: PointDto[]): Promise<RecognitionResultDto> {
  const formData = new FormData();
  formData.set("file", file);
  if (regionPolygon && regionPolygon.length >= 3) {
    formData.set("region_polygon", JSON.stringify(regionPolygon));
  }

  const response = await fetch(`${API_PREFIX}/recognition/plan`, {
    method: "POST",
    body: formData
  });

  if (!response.ok) {
    throw new Error(`Recognition request failed with status ${response.status}`);
  }

  return parseRecognitionResultDto(await response.json());
}

interface ExportProjectBundleRequest {
  projectId: string;
  metadataJson: string;
  annotatedPngBlob?: Blob;
}

export async function exportProjectBundle(
  request: ExportProjectBundleRequest
): Promise<ExportBundleDto> {
  const formData = new FormData();
  formData.set("metadata_json", request.metadataJson);

  if (request.annotatedPngBlob) {
    formData.set("annotated_png", request.annotatedPngBlob, "annotated-plan.png");
  }

  const response = await fetch(`${API_PREFIX}/projects/${request.projectId}/export`, {
    method: "POST",
    body: formData
  });

  if (!response.ok) {
    throw new Error(`Export request failed with status ${response.status}`);
  }

  return parseExportBundleDto(await response.json());
}
